### ISSUE TITLE
AssertionError [ERR_ASSERTION]: Task function must be specified

### ISSUE THREAD

**Issue by mosofoco** [cssninjaStudio/bulkit#11]
Hello - just downloaded your bulkit update (2.2.0) and I can't run gulp to build your templates.

Can you help me out to find a workaround here?

Thanks

`gulp.task('reset', function() {
    rimraf('bulma/*');
    rimraf('scss/*');
    rimraf('assets/css/*');
    rimraf('assets/fonts/*');
Michaels-MacBook-Pro:kit-demo mpo$ gulp server
assert.js:351
    throw err;
    ^

AssertionError [ERR_ASSERTION]: Task function must be specified
    at Gulp.set [as _setTask] (/Users/mpo/code/bulkit-2.2.0/kit-demo/node_modules/undertaker/lib/set-task.js:10:3)
    at Gulp.task (/Users/mpo/code/bulkit-2.2.0/kit-demo/node_modules/undertaker/lib/task.js:13:8)
    at Object.<anonymous> (/Users/mpo/code/bulkit-2.2.0/kit-demo/gulpfile.js:17:6)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:657:17)
    at require (internal/modules/cjs/helpers.js:22:18)
Michaels-MacBook-Pro:kit-demo mpo$ gulp default
assert.js:351
    throw err;
    ^

AssertionError [ERR_ASSERTION]: Task function must be specified
    at Gulp.set [as _setTask] (/Users/mpo/code/bulkit-2.2.0/kit-demo/node_modules/undertaker/lib/set-task.js:10:3)
    at Gulp.task (/Users/mpo/code/bulkit-2.2.0/kit-demo/node_modules/undertaker/lib/task.js:13:8)
    at Object.<anonymous> (/Users/mpo/code/bulkit-2.2.0/kit-demo/gulpfile.js:17:6)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:657:17)
    at require (internal/modules/cjs/helpers.js:22:18)
Michaels-MacBook-Pro:kit-demo mpo$ `

**Comment by cssninjaStudio** [comment]
What is your nodejs version ?

**Comment by cssninjaStudio** [comment]
I see, so it’s normal that you have this error. To build this template with gulp, you need node v6. Do you have a cssninja account? There is a post on how to solve this issue on our forum. You should use NVM, so you can have multiple nodejs versions installed on your machine.

**Comment by mosofoco** [comment]
I registered for an account through your support link and verified my email, but when I try to log in it says it hasn't been activated yet

**Comment by cssninjaStudio** [comment]
What is the address you registered with ?

**Comment by mosofoco** [comment]
oristian@gmail.com

**Comment by mosofoco** [comment]
I guess I can just continue to use 2.1.0 - i didn't think there we be any major dependency changes

**Comment by cssninjaStudio** [comment]
Your account is now active. You can access the forum thread by clicking on the link I left above.

**Comment by cssninjaStudio** [comment]
Well 2.2.0 shouldn’t work too, there were no dependencies changes.

**Comment by mosofoco** [comment]
Interesting.  Somehow 2.1.0 worked with my same setup.  I'm in the forum now - thanks.  Didn't realize it has something to do with node-sass.  Hey thanks for you template(s) - they're awesome.

**Comment by cssninjaStudio** [comment]
All the pleasure is for me ! You are very welcome.
